### ISSUE TITLE
LP#1320448 "menulibre crashes on start on ubuntu 14.04"

### ISSUE THREAD

**Issue by bluesabre** [bluesabre/menulibre#10]
Reported first on Launchpad at https://bugs.launchpad.net/menulibre/+bug/1320448

[LP#0](https://bugs.launchpad.net/menulibre/+bug/1320448/comments/0): *Matthias Hillebrand (mhillebr+launchpad) wrote on 2014-05-17:*

> First I tried alacarte (which was offered by the repository, but apparently does not work). After the first start and trying to change some things it crashed and does not start any more. Maybe it broke something also for menulibre? 
> 
> alacarte gives me following error:
> 
> (alacarte:14957): Gtk-CRITICAL **: gtk_accel_label_set_accel_closure: assertion 'gtk_accel_group_from_accel_closure (accel_closure) != NULL' failed
> 
> (alacarte:14957): Gtk-CRITICAL **: gtk_accel_label_set_accel_closure: assertion 'gtk_accel_group_from_accel_closure (accel_closure) != NULL' failed
> Traceback (most recent call last):
>   File "/usr/bin/alacarte", line 26, in <module>
>     main()
>   File "/usr/share/alacarte/Alacarte/MainWindow.py", line 471, in main
>     app.setMenuBasename(basename)
>   File "/usr/share/alacarte/Alacarte/MainWindow.py", line 66, in setMenuBasename
>     self.editor = MenuEditor(menu_basename)
>   File "/usr/share/alacarte/Alacarte/MenuEditor.py", line 36, in __init__
>     self.load()
>   File "/usr/share/alacarte/Alacarte/MenuEditor.py", line 49, in load
>     if not self.tree.load_sync():
> gi._glib.GError: Fehler in Zeile 1, Zeichen 1: Dokument ist leer oder enthält nur Leerraum
> 
> 
> 
> I gave menulibre a go. Unfortunately it never came up and keeps crashing with this report:  
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 2509, in do_activate
>     self.win = MenulibreWindow(self)
>   File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 339, in __init__
>     self.configure_application_treeview(builder)
>   File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 562, in configure_application_treeview
>     treestore = MenuEditor.get_treestore()
>   File "/usr/lib/python3/dist-packages/menulibre/MenuEditor.py", line 120, in get_treestore
>     menu = get_menus()[0]
>   File "/usr/lib/python3/dist-packages/menulibre/MenuEditor.py", line 182, in get_menus
>     menu = MenuEditor()
>   File "/usr/lib/python3/dist-packages/menulibre/MenuEditor.py", line 234, in __init__
>     self.load()
>   File "/usr/lib/python3/dist-packages/menulibre/MenuEditor.py", line 252, in load
>     if not self.tree.load_sync():
> gi._glib.GError: Fehler in Zeile 1, Zeichen 1: Dokument ist leer oder enthält nur Leerraum
> 
> Anything I could do or maybe even a glitch in menulibre?
> 
> thx in advance, Matthias

**Comment by bluesabre** [comment]
Same problem here (alacarte, ubuntu 14.04)
I guess the root of the problem is a file describing the structure of the startmenu. This file appears to be corrupt. I have not found a way to figure out which file this is and how to reset it.

Georg


Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1320448/comments/1) Georg Lipps - 2014-07-16 19:21:58 +0000

**Comment by bluesabre** [comment]
Delete ~/.config/gnome-applications.menu and you may restart alacarte with default settings.

Georg


Launchpad Details: [#LPC](https://bugs.launchpad.net/menulibre/+bug/1320448/comments/2) Georg Lipps - 2014-07-17 18:27:42 +0000

**Comment by bluesabre** [comment]
Ubuntu 14.04 is in ESM support. Won't fix.
