### ISSUE TITLE
ValueError: Namespace GMenu not available

### ISSUE THREAD

**Issue by BlackMage2** [bluesabre/menulibre#153]
i have installed menulibre to /usr/local and the editor doesn't start

```
$ menulibre
Traceback (most recent call last):
  File "/usr/local/bin/menulibre", line 44, in <module>
    import menulibre
  File "/usr/local/lib/python3.10/dist-packages/menulibre/__init__.py", line 23, in <module>
    from menulibre import MenulibreApplication
  File "/usr/local/lib/python3.10/dist-packages/menulibre/MenulibreApplication.py", line 34, in <module>
    from . import MenulibreTreeview, MenulibreHistory, Dialogs
  File "/usr/local/lib/python3.10/dist-packages/menulibre/MenulibreTreeview.py", line 26, in <module>
    from . import MenuEditor, MenulibreXdg, XmlMenuElementTree, util
  File "/usr/local/lib/python3.10/dist-packages/menulibre/MenuEditor.py", line 33, in <module>
    gi.require_version('GMenu', '3.0')  # noqa
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GMenu not available
``` 

why is GMenu not available?

how can i install it?

**Comment by bluesabre** [comment]
It looks like you're using a locally-installed Python. You should use your system-installed version instead for MenuLibre. Otherwise, you'll need to build and install the gi libraries for GTK apps such as MenuLibre to work. 

On Ubuntu- or Debian-based systems, the system package is: `gir1.2-gmenu-3.0`
