### ISSUE TITLE
chromebook not able to open menulibre showing this error

### ISSUE THREAD

**Issue by peepeepoopoobum** [bluesabre/menulibre#193]
No menu prefix found, MenuLibre will not function properly.
No menu prefix found, MenuLibre will not function properly.

(menulibre:6385): Gtk-WARNING **: 20:41:07.659: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

(menulibre:6385): Gtk-WARNING **: 20:41:07.766: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton
WARNING:menulibre: getDefaultMenuPrefix() 'No menu prefix found, MenuLibre will not function properly.'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 2283, in do_activate
    self.win = MenulibreWindow(self, headerbar)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 261, in __init__
    self.configure_application_treeview(builder)
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 635, in configure_application_treeview
    self.menu_load_failure()
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 314, in menu_load_failure
    box = box.get_children()[1]
          ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by joeskeen** [comment]
I receive this same error running on Debian (with no gnome or kde desktop, only openbox).

**Comment by res09392** [comment]
I also am having the same problem.  My Linux is up to date.  I was following this to install PyCharm community on Chromebook Linux.  after installing menulibre, the first time executing I get this issue.  https://www.linuxmadesimple.info/2020/11/how-to-install-pycharm-on-chromebook.html

**Comment by yoasty** [comment]
In both crostini and wsl2 menulibre does not work because it needs an active linux desktop-environment. 

In wsl2 I can start Xephyr and then run xfce4 in its own window In that widnow I can then start menulibre and add *.sh, *.jar and extracted tarballs as programs which can then run/be started from windows.   

But in crostini I cannot get that to work.

**Comment by sapeurfaire** [comment]
You can probably execute menulibre by manually prefixing the command line with the variable $XDG_MENU_PREFIX set to an appropriate value.  In a Gnome desktop that would look as such:

`$ XDG_MENU_PREFIX="gnome-" menulibre`

Details:

menulibre is looking for the value of the $XDG_MENU_PREFIX environment variable.  Per the [freedesktop spec](https://specifications.freedesktop.org/menu-spec/latest/paths.html) that'd be located under $XDG_CONFIG_DIRS.   

A Gnome desktop user might expect to see that $XDG_CONFIG_DIRS contains at least the value '/etc/xdg' with $XDG_MENU_PREFIX having a value of 'gnome-' which results in a path to '/etc/xdg/menus/gnome-applications.menu'

This would differ from the path constructed for other desktop environments.  XFCE users should probably see something like '/etc/xdg/menus/xfce-applications.menu'

It appears that menulibre assumes that you're editing in the context of the current desktop environment, which should have set up the correct environment.  There are bound to be corner cases where this doesn't happen correctly.  

There might be some value to a feature that allows a user to choose one of the "root menu" property files within $XDG_CONFIG_DIRS/menus if $XDG_MENU_PREFIX is not set (as well as being able to invoke such a feature even if that variable is in fact set; there's no reason to think that editing the menus of a different desktop environment would only occur if it's broken).

Cheers!

**Comment by yoasty** [comment]
https://github.com/bluesabre/menulibre/issues/193#issuecomment-2657369795 the solution by sapeurfaire works in crostini and wsl2 / debian. 

$ XDG_MENU_PREFIX="gnome-" menulibre
