### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 31448: invalid continuation byte (problem with locale ?)

### ISSUE THREAD

**Issue by julienm116** [bluesabre/menulibre#201]
greetings folks :)

it's been some time since i've been having this error when starting menulibre (version 2.4.0):
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 1652, in do_activate
    self.win = MenulibreWindow(self, headerbar)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 110, in __init__
    self.bad_desktop_files = util.determine_bad_desktop_files()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/menulibre/util.py", line 741, in determine_bad_desktop_files
    for line in result.stderr.decode('UTF-8').split('\n'):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 31448: invalid continuation byte

(then hangs forever)
```
here are my last try's locale :
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="C.utf8"
LC_NUMERIC="C.utf8"
LC_TIME="C.utf8"
LC_COLLATE="C.utf8"
LC_MONETARY="C.utf8"
LC_MESSAGES="C.utf8"
LC_PAPER="C.utf8"
LC_NAME="C.utf8"
LC_ADDRESS="C.utf8"
LC_TELEPHONE="C.utf8"
LC_MEASUREMENT="C.utf8"
LC_IDENTIFICATION="C.utf8"
LC_ALL=C.utf8
```
(note i'm in France but except for a few specific locale types, i usually use `en_US.UTF-8` and no LC_ALL)

i've tried several LC_ALL value (C, C.utf8,...) but i always hit the `UnicodeDecodeError` with different 'codec' (whatever that may be) and i couldn't find a thread explaining what what the issue nor how to fix it

this makes me really desperate ! if someone could lend me a hand with this please i would greatly appreciate it ^^

tia,
-J.

**Comment by julienm116** [comment]
replying to myself, as this may help others like me clueless in python

here is the workaround i found while trying tinkering, i edited `/usr/lib/python3/dist-packages/menulibre/util.py ` (adapt to your install path), line 741 was  : `for line in result.stderr.decode('UTF-8').split('\n'):` in sub-routine `def determine_bad_desktop_files():`
i replaced UTF-8 with `ISO-8859-1` in decode argument (i guess that depending on your language you may need to adapt which encoding to use )

once this change was made application was working anew 🎉 

i must have somewhere an item with specific latin-1 character that doesn't exist in UTF-8, however it shouldn't stop the application from starting (even it just displays some undef char when stumbling upon the unknown ones, imho)

there might be a better way to fix this, but ... afaic whatever works

**Comment by julienm116** [comment]
(re-opening for a while, in case someone has a better fix)

**Comment by tburba** [comment]
For me 2.4.0 hangs forever, too, although with a different locale and the crash is elsewhere.

```
 File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 1652, in do_activate
    self.win = MenulibreWindow(self, headerbar)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 83, in __init__
    self.configure_application_actions()
  File "/usr/lib/python3/dist-packages/menulibre/MenulibreApplication.py", line 343, in configure_application_actions
    label=_('Add _Launcher…'),
          ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'locale' codec can't decode byte 0xe2 in position 13: decoding error
```

**Why cant' the code use a hardcoded UTF_8 for its own constants?** By the way, the file is encoded correctly and xed displays  U+2026 as expected.

In good ole' days everybody was using the three dots, "...". I tried to update the file accordingly. The program then crashed in IconEntry.py with another occurrence of the Unicode ellipsis.

My terminal was displaying the following:

```
$locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

After `sudo locale-gen en_US.UTF-8 ; export LANG=en_US.UTF-8 LANGUAGE=en_US.en LC_ALL=en_US.UTF-8` the problem went away. Don't remember why I needed LC_ALL=C, probably I'll regret this change after a reboot.
