### ISSUE TITLE
It immediently closes after starting

### ISSUE THREAD

**Issue by Toadfield** [bluesabre/menulibre#67]
I installed it for the first time.
Every time I try to start it,it starts and after a second it closes.
I use Manjaro Kde from the official Repositories.
Edit:
If I run it in Terminal,I get this:
(menulibre:88491): Gtk-WARNING **: 22:33:11.054: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(menulibre:88491): Gtk-WARNING **: 22:33:11.054: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(menulibre:88491): Gtk-WARNING **: 22:33:11.054: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 22:33:11.068: Failed to load module "appmenu-gtk-module"

(menulibre:88491): Gtk-WARNING **: 22:33:11.110: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

(menulibre:88491): Gtk-WARNING **: 22:33:11.145: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/menulibre/MenulibreApplication.py", line 2217, in do_activate
    self.win = MenulibreWindow(self, headerbar)
  File "/usr/lib/python3.8/site-packages/menulibre/MenulibreApplication.py", line 250, in __init__
    self.configure_application_treeview(builder)
  File "/usr/lib/python3.8/site-packages/menulibre/MenulibreApplication.py", line 589, in configure_application_treeview
    self.treeview = MenulibreTreeview.Treeview(self, builder)
  File "/usr/lib/python3.8/site-packages/menulibre/MenulibreTreeview.py", line 48, in __init__
    self._configure_treeview(builder)
  File "/usr/lib/python3.8/site-packages/menulibre/MenulibreTreeview.py", line 59, in _configure_treeview
    treestore = MenuEditor.get_treestore()
  File "/usr/lib/python3.8/site-packages/menulibre/MenuEditor.py", line 122, in get_treestore
    menu = get_menus()[0]
  File "/usr/lib/python3.8/site-packages/menulibre/MenuEditor.py", line 191, in get_menus
    menu = MenuEditor()
  File "/usr/lib/python3.8/site-packages/menulibre/MenuEditor.py", line 246, in __init__
    self.load()
  File "/usr/lib/python3.8/site-packages/menulibre/MenuEditor.py", line 264, in load
    if not self.tree.load_sync():
gi.repository.GLib.Error: g-io-error-quark: Failed to look up menu_file for "kf5-applications.menu"
 (0)

**Comment by sluedecke** [comment]
ArchLinux here - same error.

strace reveals that menulibre wants to access `$HOME/.config/menus/kf5-applications.menu` and `/etc/xdg/menus/kf5-applications.menu` but neither are present on my system.

I made it run by copying a random .menu file from within `$HOME/.config/menus` to `$HOME/.config/menus/kf5-applications.menu`

**Comment by bluesabre** [comment]
This should be resolved with the above commit. Thanks for submitting this issue!
