### ISSUE TITLE
Flathub version fails to update launchers

### ISSUE THREAD

**Issue by bluesabre** [bluesabre/menulibre#91]
```
bluesabre@elementaryvm:~$ flatpak run org.bluesabre.MenuLibre 
Gtk-Message: 19:00:43.182: Failed to load module "canberra-gtk-module"

(menulibre:3): Gtk-WARNING **: 19:00:43.210: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

(menulibre:3): Gtk-WARNING **: 19:00:43.316: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/menulibre/MenulibreApplication.py", line 2128, in on_save_launcher_cb
    self.save_launcher()
  File "/app/lib/python3.9/site-packages/menulibre/MenulibreApplication.py", line 1913, in save_launcher
    self.treeview.xdg_menu_install(filename)
  File "/app/lib/python3.9/site-packages/menulibre/MenulibreTreeview.py", line 711, in xdg_menu_install
    MenulibreXdg.desktop_menu_install(parents, [filename])
  File "/app/lib/python3.9/site-packages/menulibre/MenulibreXdg.py", line 213, in desktop_menu_install
    subprocess.call(cmd_list)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-desktop-menu'
```

**Comment by bluesabre** [comment]
Closing in favor of https://github.com/flathub/org.bluesabre.MenuLibre/issues/3
